apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: development
spec:
  ports:
  - port: 27017
  selector:
    app: mongodb
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongodb
  namespace: development
spec:
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:3.6
        name: mongodb
        env:
        # Use secret in real usage
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: tpv-backend-secret
              key: MONGO_INITDB_ROOT_USERNAME
        # Use secret in real usage
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tpv-backend-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        ports:
        - containerPort: 27017
          name: mongodb
